sudo: required

services:
  - docker

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: cpp

env:
    - CXX=g++-6 CXX_PACKAGE=g++-6
    - CXX=clang++-6.0 CXX_PACKAGE=clang-6.0

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - docker exec -t ubuntu-test bash -c "apt-get update;
    apt-get install -y cmake;
# Minimum required
    apt-get install -y libglew-dev libfreetype6-dev;
# GL context and window libraries
    apt-get install -y libsdl2-dev libglfw3-dev libegl1-mesa-dev;
# Image libs
    apt-get install -y libpng-dev libfreeimage-dev libfreeimageplus-dev;
# sound
    apt-get install -y libopenal-dev libopus-dev libopusfile-dev;
# misc
    apt-get install -y libassimp-dev libeigen3-dev ffmpeg;
    add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    apt-get update;
    apt-get install -y $CXX"

script:
  - docker exec -t ubuntu-test bash -c "cd /travis;
    mkdir build;
    cd build;
    cmake -DCMAKE_CXX_COMPILER=$CXX ..;
    cmake ..;
    make -j2;" 

