language: cpp
compiler: clang
branches:
    only:
        - master
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - libglew-dev
      - libglm-dev
      - libfreetype6-dev
      - libsdl2-dev
      - libpng-dev
script:
    - mkdir build
    - cd build
    - cmake  ..
    - cmake --build .
