sudo: required
dist: xenial
services:
  - docker

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: cpp

# - SAIGA_CXX=clang++-7 CXX_PACKAGE=clang-7
env:
    - SAIGA_CXX=g++-8 CXX_PACKAGE=g++-8

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - docker exec -t ubuntu-test bash -c "add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    apt-get update;
    apt-get install -y $CXX_PACKAGE;
    apt-get install -y cmake;
    apt-get install -y libfreetype6-dev libglm-dev;
    apt-get install -y libegl1-mesa-dev;
    apt-get install -y libsdl2-dev libglfw3-dev;
    apt-get install -y libpng-dev libfreeimage-dev libfreeimageplus-dev;
    apt-get install -y libopenal-dev libopus-dev libopusfile-dev;
    apt-get install -y libavutil-dev libavcodec-dev libavresample-dev libswscale-dev libavformat-dev;
    apt-get install -y libassimp-dev libeigen3-dev libsuitesparse-dev;"

script:
  - docker exec -t ubuntu-test bash -c "cd /travis;
    mkdir build;
    cd build;
    cmake -DCMAKE_CXX_COMPILER=$SAIGA_CXX ..;
    cmake ..;
    make;" 

