# This script is partially copied from the ceres-solver:
# https://github.com/ceres-solver/ceres-solver/blob/master/.travis.yml

language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    env: CXX=g++-8
  - os: linux
    dist: bionic
    sudo: required
    compiler: clang
    env: CXX=clang++-8

env:
  - OMP_NUM_THREADS=4
  
before_install:
  - sudo apt-get update -qq
  
install:
   - sudo apt-get install -y cmake;
   - sudo apt-get install -y g++-8;
   - sudo apt-get install -y clang-8;
   - sudo apt-get install -y libfreetype6-dev libglm-dev;
   - sudo apt-get install -y libegl1-mesa-dev;
   - sudo apt-get install -y libsdl2-dev libglfw3-dev;
   - sudo apt-get install -y libpng-dev libfreeimage-dev libfreeimageplus-dev;
   - sudo apt-get install -y libopenal-dev libopus-dev libopusfile-dev;
   - sudo apt-get install -y libavutil-dev libavcodec-dev libavresample-dev libswscale-dev libavformat-dev;
   - sudo apt-get install -y libassimp-dev libeigen3-dev libsuitesparse-dev;

before_script:
  - mkdir /tmp/saiga-build
  - cd /tmp/saiga-build
  
script:
  - cmake $TRAVIS_BUILD_DIR 
  - make -j 4
  - sudo make install
  - ctest --output-on-failure -j 4

notifications:
  email:
    - darius.rueckert@fau.de
