# This script is partially copied from the ceres-solver:
# https://github.com/ceres-solver/ceres-solver/blob/master/.travis.yml

language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    env: CXX=g++-8
  - os: linux
    dist: bionic
    sudo: required
    compiler: clang
    env: CXX=clang++-8
  - os: osx
    osx_image: xcode11.2
  - os: windows

env:
  - OMP_NUM_THREADS=4
  
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; fi

  
install:
   - if [ $TRAVIS_OS_NAME = linux ]; then $TRAVIS_BUILD_DIR/travis/install_travis_linux_deps.sh; fi
   - if [ $TRAVIS_OS_NAME = osx ]; then $TRAVIS_BUILD_DIR/travis/install_travis_osx_deps.sh; fi

before_script:
  - mkdir /tmp/saiga-build
  - cd /tmp/saiga-build
  
script:
  - cmake $TRAVIS_BUILD_DIR 
  - cmake --build . -j4
  - sudo make install
  - ctest --output-on-failure -j 4

notifications:
  email:
    - darius.rueckert@fau.de
